/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var wison = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,13],$V1=[1,17],$V2=[1,19],$V3=[1,18],$V4=[13,15],$V5=[37,39,40,41],$V6=[19,20],$V7=[2,30],$V8=[1,36],$V9=[1,35],$Va=[1,44],$Vb=[1,41],$Vc=[1,42],$Vd=[1,43],$Ve=[16,19,20,40],$Vf=[1,49],$Vg=[19,20,33],$Vh=[16,19,20,27,28,32,33],$Vi=[16,19,20,24,25,26,27,28,32,33];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"wison_program":3,"WISON_KW":4,"WISON_START":5,"lex_block":6,"syntax_block":7,"WISON_END":8,"EOF":9,"LEX_KW":10,"LEX_START":11,"lex_statements":12,"LEX_END":13,"lex_statement":14,"TERMINAL_KW":15,"TERMINAL_ID":16,"ASSIGN_LEX":17,"regex_expression":18,"SEMICOLON":19,"OR":20,"regex_term":21,"regex_factor":22,"regex_atom":23,"KLEENE_STAR":24,"KLEENE_PLUS":25,"OPTIONAL":26,"STRING_LITERAL":27,"LBRACKET":28,"ALPHA_RANGE":29,"RBRACKET":30,"DIGIT_RANGE":31,"LPAREN":32,"RPAREN":33,"SYNTAX_KW":34,"SYNTAX_START":35,"syntax_statements":36,"SYNTAX_END":37,"syntax_statement":38,"NO_TERMINAL_KW":39,"NON_TERMINAL_ID":40,"INITIAL_SIM_KW":41,"ASSIGN_SYNTAX":42,"production_rules":43,"production_rule":44,"symbol_sequence":45,"symbol":46,"$accept":0,"$end":1},
terminals_: {2:"error",4:"WISON_KW",5:"WISON_START",8:"WISON_END",9:"EOF",10:"LEX_KW",11:"LEX_START",13:"LEX_END",15:"TERMINAL_KW",16:"TERMINAL_ID",17:"ASSIGN_LEX",19:"SEMICOLON",20:"OR",24:"KLEENE_STAR",25:"KLEENE_PLUS",26:"OPTIONAL",27:"STRING_LITERAL",28:"LBRACKET",29:"ALPHA_RANGE",30:"RBRACKET",31:"DIGIT_RANGE",32:"LPAREN",33:"RPAREN",34:"SYNTAX_KW",35:"SYNTAX_START",37:"SYNTAX_END",39:"NO_TERMINAL_KW",40:"NON_TERMINAL_ID",41:"INITIAL_SIM_KW",42:"ASSIGN_SYNTAX"},
productions_: [0,[3,6],[6,4],[12,2],[12,1],[12,0],[14,5],[18,3],[18,1],[21,1],[21,2],[22,1],[22,2],[22,2],[22,2],[23,1],[23,3],[23,3],[23,3],[23,1],[7,4],[36,2],[36,1],[36,0],[38,3],[38,3],[38,4],[43,3],[43,1],[44,1],[44,0],[45,2],[45,1],[46,1],[46,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

      this.$ = {
        type: 'WisonProgram',
        terminals: $$[$0-3].terminals || [],
        nonTerminals: $$[$0-2].nonTerminals || [],
        productions: $$[$0-2].productions || [],
        initialSymbol: $$[$0-2].initialSymbol || null,
        lexBlock: $$[$0-3],
        syntaxBlock: $$[$0-2]
      };
      return this.$;
    
break;
case 2:

      this.$ = {
        type: 'LexBlock',
        terminals: $$[$0-1]
      };
    
break;
case 3: case 31:

      $$[$0-1].push($$[$0]);
      this.$ = $$[$0-1];
    
break;
case 4: case 28: case 32:

      this.$ = [$$[$0]];
    
break;
case 5:

      this.$ = [];
    
break;
case 6:

      this.$ = {
        type: 'TerminalDeclaration',
        name: $$[$0-3],
        expression: $$[$0-1]
      };
    
break;
case 7:

      this.$ = {
        type: 'OrExpression',
        left: $$[$0-2],
        right: $$[$0]
      };
    
break;
case 8: case 9: case 11:

      this.$ = $$[$0];
    
break;
case 10:

      this.$ = {
        type: 'ConcatenationExpression',
        left: $$[$0-1],
        right: $$[$0]
      };
    
break;
case 12:

      this.$ = {
        type: 'KleeneStarExpression',
        expression: $$[$0-1]
      };
    
break;
case 13:

      this.$ = {
        type: 'KleenePlusExpression', 
        expression: $$[$0-1]
      };
    
break;
case 14:

      this.$ = {
        type: 'OptionalExpression',
        expression: $$[$0-1]
      };
    
break;
case 15:

      this.$ = {
        type: 'StringLiteral',
        value: $$[$0]
      };
    
break;
case 16:

      this.$ = {
        type: 'CharacterRange',
        range: 'aA-zZ'
      };
    
break;
case 17:

      this.$ = {
        type: 'CharacterRange', 
        range: '0-9'
      };
    
break;
case 18:

      this.$ = {
        type: 'GroupExpression',
        expression: $$[$0-1]
      };
    
break;
case 19:

      this.$ = {
        type: 'TerminalReference',
        name: $$[$0]
      };
    
break;
case 20:

      this.$ = {
        type: 'SyntaxBlock',
        nonTerminals: $$[$0-1].nonTerminals || [],
        initialSymbol: $$[$0-1].initialSymbol || null,
        productions: $$[$0-1].productions || []
      };
    
break;
case 21:

      if ($$[$0].type === 'NonTerminalDeclaration') {
        $$[$0-1].nonTerminals = $$[$0-1].nonTerminals || [];
        $$[$0-1].nonTerminals.push($$[$0]);
      } else if ($$[$0].type === 'InitialSymbolDeclaration') {
        $$[$0-1].initialSymbol = $$[$0].symbol;
      } else if ($$[$0].type === 'ProductionRule') {
        $$[$0-1].productions = $$[$0-1].productions || [];
        $$[$0-1].productions.push($$[$0]);
      }
      this.$ = $$[$0-1];
    
break;
case 22:

      this.$ = {
        nonTerminals: [],
        productions: [],
        initialSymbol: null
      };
      
      if ($$[$0].type === 'NonTerminalDeclaration') {
        this.$.nonTerminals.push($$[$0]);
      } else if ($$[$0].type === 'InitialSymbolDeclaration') {
        this.$.initialSymbol = $$[$0].symbol;
      } else if ($$[$0].type === 'ProductionRule') {
        this.$.productions.push($$[$0]);
      }
    
break;
case 23:

      this.$ = {
        nonTerminals: [],
        productions: [],
        initialSymbol: null
      };
    
break;
case 24:

      this.$ = {
        type: 'NonTerminalDeclaration',
        name: $$[$0-1]
      };
    
break;
case 25:

      this.$ = {
        type: 'InitialSymbolDeclaration',
        symbol: $$[$0-1]
      };
    
break;
case 26:

      this.$ = {
        type: 'ProductionRule',
        leftSide: $$[$0-3],
        rightSides: $$[$0-1]
      };
    
break;
case 27:

      $$[$0-2].push($$[$0]);
      this.$ = $$[$0-2];
    
break;
case 29:

      this.$ = {
        type: 'Production',
        symbols: $$[$0]
      };
    
break;
case 30:

      this.$ = {
        type: 'Production',
        symbols: []
      };
    
break;
case 33:

      this.$ = {
        type: 'NonTerminalSymbol',
        name: $$[$0]
      };
    
break;
case 34:

      this.$ = {
        type: 'TerminalSymbol',
        name: $$[$0]
      };
    
break;
}
},
table: [{3:1,4:[1,2]},{1:[3]},{5:[1,3]},{6:4,10:[1,5]},{7:6,34:[1,7]},{11:[1,8]},{8:[1,9]},{35:[1,10]},{12:11,13:[2,5],14:12,15:$V0},{9:[1,14]},{36:15,37:[2,23],38:16,39:$V1,40:$V2,41:$V3},{13:[1,20],14:21,15:$V0},o($V4,[2,4]),{16:[1,22]},{1:[2,1]},{37:[1,23],38:24,39:$V1,40:$V2,41:$V3},o($V5,[2,22]),{40:[1,25]},{40:[1,26]},{42:[1,27]},{34:[2,2]},o($V4,[2,3]),{17:[1,28]},{8:[2,20]},o($V5,[2,21]),{19:[1,29]},{19:[1,30]},o($V6,$V7,{43:31,44:32,45:33,46:34,16:$V8,40:$V9}),{16:$Va,18:37,21:38,22:39,23:40,27:$Vb,28:$Vc,32:$Vd},o($V5,[2,24]),o($V5,[2,25]),{19:[1,45],20:[1,46]},o($V6,[2,28]),o($V6,[2,29],{46:47,16:$V8,40:$V9}),o($Ve,[2,32]),o($Ve,[2,33]),o($Ve,[2,34]),{19:[1,48],20:$Vf},o($Vg,[2,8],{23:40,22:50,16:$Va,27:$Vb,28:$Vc,32:$Vd}),o($Vh,[2,9]),o($Vh,[2,11],{24:[1,51],25:[1,52],26:[1,53]}),o($Vi,[2,15]),{29:[1,54],31:[1,55]},{16:$Va,18:56,21:38,22:39,23:40,27:$Vb,28:$Vc,32:$Vd},o($Vi,[2,19]),o($V5,[2,26]),o($V6,$V7,{45:33,46:34,44:57,16:$V8,40:$V9}),o($Ve,[2,31]),o($V4,[2,6]),{16:$Va,21:58,22:39,23:40,27:$Vb,28:$Vc,32:$Vd},o($Vh,[2,10]),o($Vh,[2,12]),o($Vh,[2,13]),o($Vh,[2,14]),{30:[1,59]},{30:[1,60]},{20:$Vf,33:[1,61]},o($V6,[2,27]),o($Vg,[2,7],{23:40,22:50,16:$Va,27:$Vb,28:$Vc,32:$Vd}),o($Vi,[2,16]),o($Vi,[2,17]),o($Vi,[2,18])],
defaultActions: {14:[2,1],20:[2,2],23:[2,20]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"case-sensitive":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* ignorar espacios, tabs, saltos de linea */
break;
case 1:/* comentario de linea - todo despues de # hasta fin de linea */
break;
case 2:/* comentario de bloque multilinea */
break;
case 3:return 4;
break;
case 4:return 10;
break;
case 5:return 34;
break;
case 6:return 15;
break;
case 7:return 39;
break;
case 8:return 41;
break;
case 9:return 5;
break;
case 10:return 8;
break;
case 11:return 35;
break;
case 12:return 37;
break;
case 13:return 11;
break;
case 14:return 13;
break;
case 15:return 17;
break;
case 16:return 42;
break;
case 17:return 20;
break;
case 18:return 19;
break;
case 19:return 32;
break;
case 20:return 33;
break;
case 21:return 28;
break;
case 22:return 30;
break;
case 23:return 24;
break;
case 24:return 25;
break;
case 25:return 26;
break;
case 26:return 29;
break;
case 27:return 31;
break;
case 28:return 16;
break;
case 29:return 40;
break;
case 30:return 27;
break;
case 31:return 'IDENTIFIER';
break;
case 32:return 'UNKNOWN';
break;
case 33:return 9;
break;
}
},
rules: [/^(?:\s+)/,/^(?:#[^\n]*)/,/^(?:\/\*([^*]|\*(?!\/))*\*\/)/,/^(?:Wison\b)/,/^(?:Lex\b)/,/^(?:Syntax\b)/,/^(?:Terminal\b)/,/^(?:No_Terminal\b)/,/^(?:Initial_Sim\b)/,/^(?:¿)/,/^(?:\?Wison\b)/,/^(?:\{\{:)/,/^(?::\}\})/,/^(?:\{:)/,/^(?::\})/,/^(?:<-)/,/^(?:<=)/,/^(?:\|)/,/^(?:;)/,/^(?:\()/,/^(?:\))/,/^(?:\[)/,/^(?:\])/,/^(?:\*)/,/^(?:\+)/,/^(?:\?)/,/^(?:aA-zZ\b)/,/^(?:0-9\b)/,/^(?:\$_[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:%_[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:'([^'\\]|\\.)*')/,/^(?:[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:.)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = wison;
exports.Parser = wison.Parser;
exports.parse = function () { return wison.parse.apply(wison, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}